### PR TITLE
Fix/removing properties from schema

### PR DESCRIPTION
**Pull request by yartman**

### CODE REVIEW

**Comment by kosecki123** [comment]
What is this PR about?

**Comment by yartman** [comment]
> What is this PR about?

"$schema" and "$id" properties on schema cause error on schema validation itself and "version" when validating payload. so i remove them before inserting schema

**Comment by kosecki123** [comment]
Please add at least 1 e2e test to make sure it works.

**Comment by yartman** [comment]
> Please add at least 1 e2e test to make sure it works.

added

**Comment by kosecki123** [comment]
The test that fails when passing a "broken" schema and returning 400 found be nice to have.

**Comment by yartman** [comment]
> The test that fails when passing a "broken" schema and returning 400 found be nice to have.
> 
> Today while testing was able to create a channel with some obvious schema error and it allowed me to do it. The when sending the message it was error 500. Btw: I think I saw schema compile throwing error in that case.

actually i am working on schema validation itself. i'll address it in separate pr tomorrow

**Review by kosecki123 — APPROVED** [review]

**Pull request merged**
