### PR TITLE
Fix: support date-time in json schema

### PR DESCRIPTION
**Pull request by yartman**
this pr is for adding date-time format ajv package which is used for json schema validation

### CODE REVIEW

**Review by kosecki123 — APPROVED** [review]

**Comment by kosecki123** [comment]
Is there a way to add all possible formats rather than hand picking ?

**Comment by yartman** [comment]
these formats can be added
https://www.npmjs.com/package/ajv-formats?activeTab=readme#:~:text=The%20package%20defines%20these%20formats%3A

should i them all?

**Comment by kosecki123** [comment]
> these formats can be added https://www.npmjs.com/package/ajv-formats?activeTab=readme#:~:text=The%20package%20defines%20these%20formats%3A
> 
> should i add them all?

Why not just

```
addFormats(ajv)
```

is there a huge performance impact between `fast` and `full`?

**Comment by yartman** [comment]
> > these formats can be added https://www.npmjs.com/package/ajv-formats?activeTab=readme#:~:text=The%20package%20defines%20these%20formats%3A
> > should i add them all?
> 
> Why not just
> 
> ```
> addFormats(ajv)
> ```
> 
> is there a huge performance impact between `fast` and `full`?

actually i tested back then with full mode and some date and time data provided in sample payloads couldn't pass the validation an d i had to switch fast mode with explicitly specifying formats

**Review by kosecki123 — APPROVED** [review]

**Pull request merged**
